<script>
	import { JDGBodyCopy, JDGContentBoxFloating, JDGContentContainer, JDGImage } from 'jdg-ui-svelte';
	import imageAttributesCollection from '../../image-attributes-collection';
</script>

<JDGContentContainer>
	<JDGContentBoxFloating title="ENCODE CAMPUS" subtitle="Enhancing a quirky, under-utilized site">
		<JDGBodyCopy paddingTop="0" textAlign="center" fontSizeMultiplier={0.75}>
			<i>
				This is part of a series of experimental 3D models
				<br /> built while working on the
				<a href="https://www.formit.autodesk.com/">Autodesk FormIt</a> software team.
			</i>
		</JDGBodyCopy>
		<JDGBodyCopy paddingTop="0">
			An L-shaped vacant lot at 15th and Champa in Denver, Colorado becomes a new campus for a
			fictional software company, including ground-level retail and a new plaza which provides a
			gathering area for the neighboring buildings.
			<br /><br />
			The facade of the building, including the floor plates, canopies, glazing, mullions, and louvers,
			are generated by Dynamo and driven off of a single polyline at the building edge, defining the
			shape of all elements.
		</JDGBodyCopy>
		<JDGImage
			imageAttributes={imageAttributesCollection.exp.encode_campus_after}
			maxHeight="600px"
			fillContainer={false}
			showBlurInUnfilledSpace={true}
			showCaption={true}
		/>
		<JDGBodyCopy>
			This model was created to demonstrate the power of FormIt and Dynamo, specifically the
			SelectFromFormIt node, enabling geometric generation and modification more quickly than ever.
		</JDGBodyCopy>
	</JDGContentBoxFloating>
</JDGContentContainer>
